/* ARMv8 recommended implementation defined event types */
#define ARMV8_IMPDEF_PERFCTR_L1D_CACHE_RD           0x0040
#define ARMV8_IMPDEF_PERFCTR_L1D_CACHE_WR           0x0041
#define ARMV8_IMPDEF_PERFCTR_L1D_CACHE_REFILL_RD        0x0042
#define ARMV8_IMPDEF_PERFCTR_L1D_CACHE_REFILL_WR        0x0043
#define ARMV8_IMPDEF_PERFCTR_L1D_CACHE_REFILL_INNER     0x0044
#define ARMV8_IMPDEF_PERFCTR_L1D_CACHE_REFILL_OUTER     0x0045
#define ARMV8_IMPDEF_PERFCTR_L1D_CACHE_WB_VICTIM        0x0046
#define ARMV8_IMPDEF_PERFCTR_L1D_CACHE_WB_CLEAN         0x0047
#define ARMV8_IMPDEF_PERFCTR_L1D_CACHE_INVAL            0x0048

#define ARMV8_IMPDEF_PERFCTR_L1D_TLB_REFILL_RD          0x004C
#define ARMV8_IMPDEF_PERFCTR_L1D_TLB_REFILL_WR          0x004D
#define ARMV8_IMPDEF_PERFCTR_L1D_TLB_RD             0x004E
#define ARMV8_IMPDEF_PERFCTR_L1D_TLB_WR             0x004F
#define ARMV8_IMPDEF_PERFCTR_L2D_CACHE_RD           0x0050
#define ARMV8_IMPDEF_PERFCTR_L2D_CACHE_WR           0x0051
#define ARMV8_IMPDEF_PERFCTR_L2D_CACHE_REFILL_RD        0x0052
#define ARMV8_IMPDEF_PERFCTR_L2D_CACHE_REFILL_WR        0x0053

#define ARMV8_IMPDEF_PERFCTR_L2D_CACHE_WB_VICTIM        0x0056
#define ARMV8_IMPDEF_PERFCTR_L2D_CACHE_WB_CLEAN         0x0057
#define ARMV8_IMPDEF_PERFCTR_L2D_CACHE_INVAL            0x0058

#define ARMV8_IMPDEF_PERFCTR_L2D_TLB_REFILL_RD          0x005C
#define ARMV8_IMPDEF_PERFCTR_L2D_TLB_REFILL_WR          0x005D
#define ARMV8_IMPDEF_PERFCTR_L2D_TLB_RD             0x005E
#define ARMV8_IMPDEF_PERFCTR_L2D_TLB_WR             0x005F
#define ARMV8_IMPDEF_PERFCTR_BUS_ACCESS_RD          0x0060
#define ARMV8_IMPDEF_PERFCTR_BUS_ACCESS_WR          0x0061
#define ARMV8_IMPDEF_PERFCTR_BUS_ACCESS_SHARED          0x0062
#define ARMV8_IMPDEF_PERFCTR_BUS_ACCESS_NOT_SHARED      0x0063
#define ARMV8_IMPDEF_PERFCTR_BUS_ACCESS_NORMAL          0x0064
#define ARMV8_IMPDEF_PERFCTR_BUS_ACCESS_PERIPH          0x0065
#define ARMV8_IMPDEF_PERFCTR_MEM_ACCESS_RD          0x0066
#define ARMV8_IMPDEF_PERFCTR_MEM_ACCESS_WR          0x0067
#define ARMV8_IMPDEF_PERFCTR_UNALIGNED_LD_SPEC          0x0068
#define ARMV8_IMPDEF_PERFCTR_UNALIGNED_ST_SPEC          0x0069
#define ARMV8_IMPDEF_PERFCTR_UNALIGNED_LDST_SPEC        0x006A

#define ARMV8_IMPDEF_PERFCTR_LDREX_SPEC             0x006C
#define ARMV8_IMPDEF_PERFCTR_STREX_PASS_SPEC            0x006D
#define ARMV8_IMPDEF_PERFCTR_STREX_FAIL_SPEC            0x006E
#define ARMV8_IMPDEF_PERFCTR_STREX_SPEC             0x006F
#define ARMV8_IMPDEF_PERFCTR_LD_SPEC                0x0070
#define ARMV8_IMPDEF_PERFCTR_ST_SPEC                0x0071
#define ARMV8_IMPDEF_PERFCTR_LDST_SPEC              0x0072
#define ARMV8_IMPDEF_PERFCTR_DP_SPEC                0x0073
#define ARMV8_IMPDEF_PERFCTR_ASE_SPEC               0x0074
#define ARMV8_IMPDEF_PERFCTR_VFP_SPEC               0x0075
#define ARMV8_IMPDEF_PERFCTR_PC_WRITE_SPEC          0x0076
#define ARMV8_IMPDEF_PERFCTR_CRYPTO_SPEC            0x0077
#define ARMV8_IMPDEF_PERFCTR_BR_IMMED_SPEC          0x0078
#define ARMV8_IMPDEF_PERFCTR_BR_RETURN_SPEC         0x0079
#define ARMV8_IMPDEF_PERFCTR_BR_INDIRECT_SPEC           0x007A

#define ARMV8_IMPDEF_PERFCTR_ISB_SPEC               0x007C
#define ARMV8_IMPDEF_PERFCTR_DSB_SPEC               0x007D
#define ARMV8_IMPDEF_PERFCTR_DMB_SPEC               0x007E

#define ARMV8_IMPDEF_PERFCTR_EXC_UNDEF              0x0081
#define ARMV8_IMPDEF_PERFCTR_EXC_SVC                0x0082
#define ARMV8_IMPDEF_PERFCTR_EXC_PABORT             0x0083
#define ARMV8_IMPDEF_PERFCTR_EXC_DABORT             0x0084

#define ARMV8_IMPDEF_PERFCTR_EXC_IRQ                0x0086
#define ARMV8_IMPDEF_PERFCTR_EXC_FIQ                0x0087
#define ARMV8_IMPDEF_PERFCTR_EXC_SMC                0x0088

#define ARMV8_IMPDEF_PERFCTR_EXC_HVC                0x008A
#define ARMV8_IMPDEF_PERFCTR_EXC_TRAP_PABORT            0x008B
#define ARMV8_IMPDEF_PERFCTR_EXC_TRAP_DABORT            0x008C
#define ARMV8_IMPDEF_PERFCTR_EXC_TRAP_OTHER         0x008D
#define ARMV8_IMPDEF_PERFCTR_EXC_TRAP_IRQ           0x008E
#define ARMV8_IMPDEF_PERFCTR_EXC_TRAP_FIQ           0x008F
#define ARMV8_IMPDEF_PERFCTR_RC_LD_SPEC             0x0090
#define ARMV8_IMPDEF_PERFCTR_RC_ST_SPEC             0x0091

#define ARMV8_IMPDEF_PERFCTR_L3D_CACHE_RD           0x00A0
#define ARMV8_IMPDEF_PERFCTR_L3D_CACHE_WR           0x00A1
#define ARMV8_IMPDEF_PERFCTR_L3D_CACHE_REFILL_RD        0x00A2
#define ARMV8_IMPDEF_PERFCTR_L3D_CACHE_REFILL_WR        0x00A3

#define ARMV8_IMPDEF_PERFCTR_L3D_CACHE_WB_VICTIM        0x00A6
#define ARMV8_IMPDEF_PERFCTR_L3D_CACHE_WB_CLEAN         0x00A7
#define ARMV8_IMPDEF_PERFCTR_L3D_CACHE_INVAL            0x00A8
