set -x
../../perf_case memset_malloc      -c 1 -e armv8 > memset_malloc.txt
../../perf_case memset_malloc_x2   -c 1 -e armv8 > memset_malloc_x2.txt
../../perf_case memset_mmap        -c 1 -e armv8 > memset_mmap.txt
../../perf_case memset_static_bss  -c 1 -e armv8 > memset_static_bss.txt
../../perf_case memset_static_data -c 1 -e armv8 > memset_static_data.txt
../../perf_case membw_rd_1         -c 1 -e armv8 > membw_rd_1.txt
../../perf_case membw_rd_4         -c 1 -e armv8 > membw_rd_4.txt
../../perf_case membw_rd_8         -c 1 -e armv8 > membw_rd_8.txt
../../perf_case membw_rd_1_4x      -c 1 -e armv8 > membw_rd_1_4x.txt
../../perf_case membw_rd_4_4x      -c 1 -e armv8 > membw_rd_4_4x.txt
../../perf_case membw_rd_8_4x      -c 1 -e armv8 > membw_rd_8_4x.txt
../../perf_case membw_wr_1         -c 1 -e armv8 > membw_wr_1.txt
../../perf_case membw_wr_4         -c 1 -e armv8 > membw_wr_4.txt
../../perf_case membw_wr_8         -c 1 -e armv8 > membw_wr_8.txt
../../perf_case membw_wr_1_4x      -c 1 -e armv8 > membw_wr_1_4x.txt
../../perf_case membw_wr_4_4x      -c 1 -e armv8 > membw_wr_4_4x.txt
../../perf_case membw_wr_8_4x      -c 1 -e armv8 > membw_wr_8_4x.txt
../../perf_case membw_cp_1         -c 1 -e armv8 > membw_cp_1.txt
../../perf_case membw_cp_4         -c 1 -e armv8 > membw_cp_4.txt
../../perf_case membw_cp_8         -c 1 -e armv8 > membw_cp_8.txt
../../perf_case membw_cp_1_4x      -c 1 -e armv8 > membw_cp_1_4x.txt
../../perf_case membw_cp_4_4x      -c 1 -e armv8 > membw_cp_4_4x.txt
../../perf_case membw_cp_8_4x      -c 1 -e armv8 > membw_cp_8_4x.txt
../../perf_case memlat_random      -c 1 -e armv8 > memlat_random.txt

../../perf_case memset_malloc      -c 1 -e orin >> memset_malloc.txt
../../perf_case memset_malloc_x2   -c 1 -e orin >> memset_malloc_x2.txt
../../perf_case memset_mmap        -c 1 -e orin >> memset_mmap.txt
../../perf_case memset_static_bss  -c 1 -e orin >> memset_static_bss.txt
../../perf_case memset_static_data -c 1 -e orin >> memset_static_data.txt
../../perf_case membw_rd_1         -c 1 -e orin >> membw_rd_1.txt
../../perf_case membw_rd_4         -c 1 -e orin >> membw_rd_4.txt
../../perf_case membw_rd_8         -c 1 -e orin >> membw_rd_8.txt
../../perf_case membw_rd_1_4x      -c 1 -e orin >> membw_rd_1_4x.txt
../../perf_case membw_rd_4_4x      -c 1 -e orin >> membw_rd_4_4x.txt
../../perf_case membw_rd_8_4x      -c 1 -e orin >> membw_rd_8_4x.txt
../../perf_case membw_wr_1         -c 1 -e orin >> membw_wr_1.txt
../../perf_case membw_wr_4         -c 1 -e orin >> membw_wr_4.txt
../../perf_case membw_wr_8         -c 1 -e orin >> membw_wr_8.txt
../../perf_case membw_wr_1_4x      -c 1 -e orin >> membw_wr_1_4x.txt
../../perf_case membw_wr_4_4x      -c 1 -e orin >> membw_wr_4_4x.txt
../../perf_case membw_wr_8_4x      -c 1 -e orin >> membw_wr_8_4x.txt
../../perf_case membw_cp_1         -c 1 -e orin >> membw_cp_1.txt
../../perf_case membw_cp_4         -c 1 -e orin >> membw_cp_4.txt
../../perf_case membw_cp_8         -c 1 -e orin >> membw_cp_8.txt
../../perf_case membw_cp_1_4x      -c 1 -e orin >> membw_cp_1_4x.txt
../../perf_case membw_cp_4_4x      -c 1 -e orin >> membw_cp_4_4x.txt
../../perf_case membw_cp_8_4x      -c 1 -e orin >> membw_cp_8_4x.txt
../../perf_case memlat_random      -c 1 -e orin >> memlat_random.txt
